---
- hosts: "{{ cluster }}"
  remote_user: root
  become: yes
  vars:
    ng1_ip: "{{ ng1_ip }}"
    keypair: "{{ keypair }}"

  tasks:
  - copy:
      src: /root/is-6010-245-vSCOUT.bin
      dest: /root/is-6010-245-vSCOUT.bin
      mode: 0755
  - script: /root/is-6010-245-vSCOUT.bin -s
    ignore_errors: yes
  - replace:
      path: /usr/lib/NetScout/rtm/config/nsagent_config.cfg
      regexp: 'HTTP_PORT=8080'
      replace: 'HTTP_PORT=58080'
      backup: yes
  - replace:
      path: /usr/lib/NetScout/rtm/config/nsagent_config.cfg
      regexp: 'HTTPS_PORT=8443'
      replace: 'HTTPS_PORT=58443'
  - lineinfile:
      path: /usr/lib/NetScout/rtm/config/nsagent_config.cfg
      line: "export NSCONFIG_SERVER_IP=10.0.0.111"
  - name: stop vscoutd service if its running
    service:
       name: vscoutd
       state: stopped
